### ISSUE TITLE
Constructor injection for WebService

### ISSUE THREAD

**Issue by gfox1984** [aspnet/AspNetWebFormsDependencyInjection#18]
I'm getting this error when trying to call a web service (System.Web.Services.WebService) from JS, which takes a dependency in its constructor:

`No parameterless constructor defined for this object. (status code 500)
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
at System.Web.Script.Services.RestHandler.InvokeMethod(HttpContext context, WebServiceMethodData methodData, IDictionary 2 rawParams)
at System.Web.Script.Services.RestHandler.ExecuteWebServiceCall(HttpContext context, WebServiceMethodData methodData)` 

What would it take to constructor injection work for a WebService?

**Comment by StephenMolloy** [comment]
`System.Web.Services` - while adjacent to ASP.Net/WebForms - is not part of ASP.Net. It was a predecessor to WCF. For the purposes of this repo, the Dependency Injection support added to the .Net Framework was limited to WebForms.

> **Warning**
> _This project demonstrates building a dependency injection adapter for the [Unity](https://github.com/unitycontainer/unity) IoC container. **It is a point of reference** for other adapter authors. Please note that this implementation is for demonstration purposes only and **is not being actively maintained.**_
